import type { ContentItem, StatusSummary } from '@/types/dashboard';

export const statusSummary: StatusSummary = {
  pending: 5,
  reviewing: 2,
  approved: 14,
  rejected: 3,
  total: 24,
};

export const contentItems: ContentItem[] = [
  {
    id: 'C-0142',
    title: '신규 적금 상품 런칭 SNS 카드뉴스 (5종)',
    type: 'sns',
    typeLabel: 'SNS 카드뉴스',
    advisor: '박준법',
    creator: '김지원',
    submittedAt: '2026-05-18',
    status: 'approved',
  },
  {
    id: 'C-0141',
    title: '5월 적금 이벤트 배너 - 메인페이지용',
    type: 'banner',
    typeLabel: '웹 배너',
    advisor: '박준법',
    creator: '김지원',
    submittedAt: '2026-05-17',
    status: 'rejected',
  },
  {
    id: 'C-0139',
    title: '청년 도약 적금 - 유튜브 광고 영상 스크립트',
    type: 'video',
    typeLabel: '영상 스크립트',
    advisor: '이감독',
    creator: '이현수',
    submittedAt: '2026-05-15',
    status: 'rejected',
  },
  {
    id: 'C-0137',
    title: 'MZ 타겟 카드 - 인스타그램 릴스 카피',
    type: 'other',
    typeLabel: '릴스 카피',
    advisor: '박준법',
    creator: '김지원',
    submittedAt: '2026-05-14',
    status: 'reviewing',
  },
  {
    id: 'C-0135',
    title: '주택담보대출 우대 안내 블로그 포스트',
    type: 'blog',
    typeLabel: '블로그 포스트',
    advisor: '최감리',
    creator: '박민준',
    submittedAt: '2026-05-13',
    status: 'approved',
  },
  {
    id: 'C-0133',
    title: '연금저축 절세 가이드 PDF e-book',
    type: 'ebook',
    typeLabel: 'e-book',
    advisor: '최감리',
    creator: '박민준',
    submittedAt: '2026-05-12',
    status: 'approved',
  },
  {
    id: 'C-0131',
    title: '환전 수수료 할인 이벤트 푸시 알림 문구',
    type: 'other',
    typeLabel: '푸시 문구',
    advisor: '박준법',
    creator: '이현수',
    submittedAt: '2026-05-11',
    status: 'rejected',
  },
  {
    id: 'C-0129',
    title: 'ISA 통합계좌 설명 카드뉴스 (3종)',
    type: 'sns',
    typeLabel: 'SNS 카드뉴스',
    advisor: null,
    creator: '김지원',
    submittedAt: '2026-05-10',
    status: 'pending',
  },
];
