import type { ContentItem, StatusSummary } from '@/types/dashboard';

export const advisorSummary = {
  pending: 12,
  todayDone: 7,
  todayApproved: 5,
  todayRejected: 2,
  avgDays: 1.2,
  resubmit: 3,
};

export const statusSummary: StatusSummary = {
  pending: 3,
  reviewing: 3,
  approved: 6,
  rejected: 5,
  total: 17,
};

export const contentItems: ContentItem[] = [
  {
    id: 'C-0142',
    title: '신규 적금 상품 런칭 SNS 이벤트 게시물',
    type: 'sns',
    typeLabel: 'SNS',
    advisor: '박준법',
    creator: '김지원',
    submittedAt: '2026-05-18',
    status: 'approved',
  },
  {
    id: 'C-0141',
    title: '5월 적금 이벤트 홈페이지 메인 배너',
    type: 'homepage',
    typeLabel: '홈페이지',
    advisor: '박준법',
    creator: '김지원',
    submittedAt: '2026-05-17',
    status: 'rejected',
  },
  {
    id: 'C-0140',
    title: '청년 도약 적금 카카오톡 알림톡 문구',
    type: 'kakao',
    typeLabel: '카카오톡',
    advisor: '이감독',
    creator: '이현수',
    submittedAt: '2026-05-16',
    status: 'approved',
  },
  {
    id: 'C-0139',
    title: 'MZ 타겟 카드 출시 문자 발송 문구',
    type: 'sms',
    typeLabel: '문자',
    advisor: '이감독',
    creator: '이현수',
    submittedAt: '2026-05-15',
    status: 'rejected',
  },
  {
    id: 'C-0138',
    title: '주택담보대출 우대금리 홈페이지 랜딩 페이지',
    type: 'homepage',
    typeLabel: '홈페이지',
    advisor: '최감리',
    creator: '박민준',
    submittedAt: '2026-05-14',
    status: 'reviewing',
  },
  {
    id: 'C-0137',
    title: 'ISA 통합계좌 카카오톡 채널 메시지',
    type: 'kakao',
    typeLabel: '카카오톡',
    advisor: '박준법',
    creator: '김지원',
    submittedAt: '2026-05-13',
    status: 'approved',
  },
  {
    id: 'C-0136',
    title: '연금저축 절세 안내 SNS 카드뉴스',
    type: 'sns',
    typeLabel: 'SNS',
    advisor: '최감리',
    creator: '박민준',
    submittedAt: '2026-05-12',
    status: 'approved',
  },
  {
    id: 'C-0135',
    title: '환전 수수료 할인 이벤트 문자 발송',
    type: 'sms',
    typeLabel: '문자',
    advisor: '박준법',
    creator: '이현수',
    submittedAt: '2026-05-11',
    status: 'rejected',
  },
  {
    id: 'C-0134',
    title: '신용카드 혜택 안내 홈페이지 팝업',
    type: 'homepage',
    typeLabel: '홈페이지',
    advisor: null,
    creator: '김지원',
    submittedAt: '2026-05-10',
    status: 'pending',
  },
  {
    id: 'C-0133',
    title: '외화 적금 출시 SNS 홍보 게시물',
    type: 'sns',
    typeLabel: 'SNS',
    advisor: null,
    creator: '이현수',
    submittedAt: '2026-05-09',
    status: 'pending',
  },
  {
    id: 'C-0132',
    title: '개인사업자 대출 카카오톡 비즈메시지',
    type: 'kakao',
    typeLabel: '카카오톡',
    advisor: '이감독',
    creator: '박민준',
    submittedAt: '2026-05-08',
    status: 'reviewing',
  },
  {
    id: 'C-0131',
    title: '5월 특판 정기예금 문자 안내',
    type: 'sms',
    typeLabel: '문자',
    advisor: '박준법',
    creator: '김지원',
    submittedAt: '2026-05-07',
    status: 'approved',
  },
  {
    id: 'C-0130',
    title: '앱 리뉴얼 홈페이지 소개 페이지',
    type: 'homepage',
    typeLabel: '홈페이지',
    advisor: '최감리',
    creator: '이현수',
    submittedAt: '2026-05-06',
    status: 'rejected',
  },
  {
    id: 'C-0129',
    title: '금융 건강 캠페인 SNS 시리즈',
    type: 'sns',
    typeLabel: 'SNS',
    advisor: null,
    creator: '박민준',
    submittedAt: '2026-05-05',
    status: 'pending',
  },
  {
    id: 'C-0128',
    title: '체크카드 캐시백 이벤트 카카오톡 메시지',
    type: 'kakao',
    typeLabel: '카카오톡',
    advisor: '이감독',
    creator: '김지원',
    submittedAt: '2026-05-04',
    status: 'reviewing',
  },
  {
    id: 'C-0127',
    title: '자동이체 서비스 안내 문자',
    type: 'sms',
    typeLabel: '문자',
    advisor: '박준법',
    creator: '이현수',
    submittedAt: '2026-05-03',
    status: 'rejected',
  },
  {
    id: 'C-0126',
    title: '해외직구 환율 우대 기타 홍보물',
    type: 'other',
    typeLabel: '기타',
    advisor: '최감리',
    creator: '박민준',
    submittedAt: '2026-05-02',
    status: 'approved',
  },
];
